apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  selector:
    matchLabels:
      app: react
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: react
        tier: frontend
    spec:
      containers:
        - name: con
          image: dev7495/td-react-app:v1
          ports:
          - containerPort: 3000  
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: react
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
    nodePort:
  type: NodePort
...
